name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Cucumber BDD tests
        run: npx cypress run --spec "cypress/e2e/features/toolshop.feature"

      - name: Run Cypress POM tests
        run: npx cypress run --spec "cypress/e2e/toolshop/toolshop.cy.js"